### ISSUE TITLE
The error message on redisk.save is misleading

### ISSUE THREAD

**Issue by EduardoSimon** [ArkerLabs/redisk#5] opened 2020-04-17 09:01 UTC
When a field of one event is null or undefined in an updater, due to a developer error, the output from the console is misleading. The error should point right to the updater and the field that was null || undefined.

In the following case the updater had the event.modified to null. Causing an error.

![image](https://user-images.githubusercontent.com/19764148/79552020-bf3d3580-809a-11ea-9bf3-592843e4a262.png)

And the output from the console was:

![image](https://user-images.githubusercontent.com/19764148/79551989-b64c6400-809a-11ea-80f8-6caf0cfe86ef.png)

**Comment by Nytyr** [comment] 2020-04-18 18:02
Can you send me your Entity? So I can reproduce the bug.

**Comment by EduardoSimon** [comment] 2020-04-18 18:17
In the previous example, the event.email field was null. So, in order to recreate it try to force accesing a null field of the event and persist it in a redis entity.

**Comment by Nytyr** [comment] 2020-04-18 18:20
I need the EmployeeViewModel implementation, I'm trying to update other entities with Date fields and it's working fine.

**Comment by EduardoSimon** [comment] 2020-04-18 22:13
Try to update a primary key field with null, thats what I think I am doing wrong

**Comment by Nytyr** [comment] 2020-08-18 08:26
Closing, can't reproduce.

**Closed by Nytyr** 2020-08-18 08:26 UTC
